
import React, { createContext, useState, useContext, ReactNode } from "react";

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState("en");

  // Define all translations
  const translations: Translations = {
    en: {
      // Common
      back: "Back",
      submit: "Submit",
      reset: "Reset",
      cancel: "Cancel",
      send: "Send",
      error: "Error",
      close: "Close",
      search: "Search",
      loading: "Loading...",
      allRightsReserved: "All Rights Reserved",
      
      // Home page
      heroTitle: "Revolutionizing Global Shipping with Blockchain Technology",
      heroSubtitle: "End-to-end logistics and freight forwarding services with enhanced transparency and efficiency",
      getStarted: "Get Started",
      learnMore: "Learn More",
      trackShipment: "Track Shipment",
      enterTracking: "Enter tracking number",
      requestQuote: "Request Quote",
      calculatePalletPrice: "Calculate Pallet Price",
      recentShipments: "Recent Shipments",
      status: "Status",
      deliveryDate: "Delivery Date",
      origin: "Origin",
      destination: "Destination",
      shippingServices: "Our Shipping Services",
      oceanFreight: "Ocean Freight",
      oceanFreightDescription: "Reliable and cost-effective ocean freight solutions for your cargo",
      airFreight: "Air Freight",
      airFreightDescription: "Fast and efficient air freight services for time-sensitive shipments",
      roadTransport: "Road Transport",
      roadTransportDescription: "Efficient road transport solutions for your domestic shipping needs",
      warehousing: "Warehousing",
      warehousingDescription: "Secure and flexible warehousing solutions for your storage needs",
      customs: "Customs Clearance",
      customsDescription: "Hassle-free customs clearance services for your international shipments",
      insurance: "Cargo Insurance",
      insuranceDescription: "Comprehensive cargo insurance for your valuable shipments",
      trustedBy: "Trusted by Leading Companies Worldwide",
      testimonials: "Testimonials",
      testimonialText1: "Eazy Chain has transformed our logistics operations with their innovative blockchain solution. We now have complete visibility of our supply chain.",
      testimonialAuthor1: "John Smith, Logistics Manager",
      testimonialText2: "The level of transparency and efficiency that Eazy Chain provides is unmatched. We've reduced our shipping costs by 20%.",
      testimonialAuthor2: "Sarah Johnson, Supply Chain Director",
      testimonialText3: "Eazy Chain's platform has simplified our customs clearance process and reduced delays significantly.",
      testimonialAuthor3: "Michael Brown, Operations Manager",
      aboutUs: "About Us",
      aboutUsText: "Eazy Chain is a leading blockchain-based logistics and supply chain management platform. We leverage cutting-edge technology to provide end-to-end visibility, enhanced security, and increased efficiency in global shipping.",
      contactUs: "Contact Us",
      contactUsText: "Have questions or need assistance? Our team is here to help you with all your shipping and logistics needs.",
      email: "Email",
      phone: "Phone",
      address: "Address",
      headquarters: "Headquarters",
      sendMessage: "Send Message",
      yourName: "Your Name",
      yourEmail: "Your Email",
      subject: "Subject",
      message: "Message",
      
      // Footer
      followUs: "Follow Us",
      newsletter: "Newsletter",
      subscribeText: "Subscribe to our newsletter for the latest updates",
      subscribe: "Subscribe",
      termsOfService: "Terms of Service",
      privacyPolicy: "Privacy Policy",
      
      // Navigation
      home: "Home",
      services: "Services",
      booking: "Booking",
      tracking: "Tracking",
      passengers: "Passengers",
      payment: "Payment",
      account: "Account",
      login: "Login",
      logout: "Logout",
      register: "Register",
      dashboard: "Dashboard",
      
      // Booking page
      bookingTitle: "Book Your Shipment",
      bookingSubtitle: "Fill out the form below to book your shipment",
      shipmentDetails: "Shipment Details",
      freightType: "Freight Type",
      containerCount: "Container Count",
      cargoType: "Cargo Type",
      cargoDescription: "Cargo Description",
      weight: "Weight (kg)",
      dimensions: "Dimensions (cm)",
      palletCount: "Pallet Count",
      palletType: "Pallet Type",
      specialRequirements: "Special Requirements",
      pickupDetails: "Pickup Details",
      pickupDate: "Pickup Date",
      pickupTime: "Pickup Time",
      pickupAddress: "Pickup Address",
      deliveryDetails: "Delivery Details",
      deliveryDate: "Delivery Date",
      deliveryTime: "Delivery Time",
      deliveryAddress: "Delivery Address",
      contactDetails: "Contact Details",
      contactName: "Contact Name",
      contactEmail: "Contact Email",
      contactPhone: "Contact Phone",
      companyName: "Company Name",
      bookNow: "Book Now",
      bookingReference: "Booking Reference",
      estimatedCost: "Estimated Cost",
      termsAgreement: "I agree to the terms and conditions",
      selectFreightType: "Select freight type",
      selectCargoType: "Select cargo type",
      selectPalletType: "Select pallet type",
      enterCargoDescription: "Enter cargo description",
      enterPickupAddress: "Enter pickup address",
      enterDeliveryAddress: "Enter delivery address",
      fullName: "Full Name",
      emailPlaceholder: "name@example.com",
      phonePlaceholder: "+1 (555) 000-0000",
      enterCompanyName: "Enter company name",
      needPickupService: "I need pickup service",
      checkBoxIfPickupNeeded: "Check this box if you need us to pick up your cargo",
      bookingConfirmed: "Booking Confirmed!",
      originPort: "Origin Port",
      destinationPort: "Destination Port",
      bookingRequestSubmitted: "Booking Request Submitted!",
      bookingConfirmation: "Thank you for your booking request. You will receive a confirmation email shortly.",
      selectOriginPort: "Select origin port",
      selectDestinationPort: "Select destination port",
      departureDate: "Departure Date",
      selectDepartureDate: "Select departure date",
      noDescriptionFound: "No description found",
      yourBookingReference: "Your Booking Reference",
      keepReferenceForPaymentTracking: "Please keep this reference for payment and tracking",
      selectCargoDescription: "Select cargo description",
      scanQrCodeForPayment: "Scan QR code for payment",
      payNow: "Pay Now",
      newBooking: "New Booking",
      submitting: "Submitting...",
      submitBookingRequest: "Submit Booking Request",
      
      // Tracking page
      trackingTitle: "Track Your Shipment",
      trackingSubtitle: "Enter your tracking number to see the status of your shipment",
      trackButton: "Track",
      trackingNumber: "Tracking Number",
      enterTrackingNumber: "Enter tracking number",
      shipmentNotFound: "Shipment not found",
      shipmentDetails: "Shipment Details",
      currentStatus: "Current Status",
      statusHistory: "Status History",
      statusDate: "Date",
      statusLocation: "Location",
      statusDetails: "Details",
      latestUpdate: "Latest Update",
      estimatedArrival: "Estimated Arrival",
      departurePort: "Departure Port",
      arrivalPort: "Arrival Port",
      transitTime: "Transit Time",
      days: "days",
      documentType: "Document Type",
      documentNumber: "Document Number",
      vessel: "Vessel",
      voyage: "Voyage",
      
      // Payment page
      paymentTitle: "Payment",
      securePayment: "Secure Payment",
      paymentDesc: "Complete your payment securely to confirm your booking",
      paymentDetails: "Payment Details",
      bookingId: "Booking ID",
      amount: "Amount",
      currency: "Currency",
      paymentMethod: "Payment Method",
      cardNumber: "Card Number",
      cardholderName: "Cardholder Name",
      expiryDate: "Expiry Date",
      cvv: "CVV",
      billingAddress: "Billing Address",
      city: "City",
      country: "Country",
      postalCode: "Postal Code",
      pay: "Pay",
      processing: "Processing...",
      paymentSuccessful: "Payment Successful!",
      paymentFailed: "Payment Failed!",
      tryAgain: "Please try again or use a different payment method.",
      backToBooking: "Back to Booking",
      transactionId: "Transaction ID",
      transactionDate: "Transaction Date",
      shipmentId: "Shipment ID",
      description: "Description",
      weight: "Weight",
      units: "units",
      costBreakdown: "Cost Breakdown",
      freightCost: "Freight Cost",
      handlingFees: "Handling Fees",
      documentation: "Documentation",
      insurance: "Insurance",
      totalAmount: "Total Amount",
      estimatedDelivery: "Estimated Delivery",
      loadingPayment: "Loading payment details...",
      verifyBookingReference: "Verify Booking Reference",
      enterBookingReference: "Enter your booking reference",
      verify: "Verify",
      verifying: "Verifying...",
      verified: "Verified",
      referenceVerificationFailed: "Booking reference verification failed",
      referenceNotFound: "Booking reference not found",
      invalidReference: "Invalid booking reference",
      

      // Passenger booking page
      passengerBookingTitle: "Passenger Booking",
      passengerDetails: "Passenger Details",
      travelDetails: "Travel Details",
      personalInformation: "Personal Information",
      firstName: "First Name",
      lastName: "Last Name",
      dateOfBirth: "Date of Birth",
      nationality: "Nationality",
      passportNumber: "Passport Number",
      passportExpiry: "Passport Expiry Date",
      departurePort: "Departure Port",
      arrivalPort: "Arrival Port",
      departureDate: "Departure Date",
      returnDate: "Return Date (Optional)",
      adults: "Adults",
      children: "Children",
      infants: "Infants",
      cabinClass: "Cabin Class",
      economy: "Economy",
      business: "Business",
      firstClass: "First Class",
      mealPreference: "Meal Preference",
      standard: "Standard",
      vegetarian: "Vegetarian",
      vegan: "Vegan",
      glutenFree: "Gluten Free",
      kosher: "Kosher",
      halal: "Halal",
      specialAssistance: "Special Assistance",
      wheelchair: "Wheelchair",
      visualAssistance: "Visual Assistance",
      hearingAssistance: "Hearing Assistance",
      none: "None",
      emergencyContact: "Emergency Contact",
      relationship: "Relationship",
      totalCost: "Total Cost",
      termsAndConditions: "Terms and Conditions",
      iAgree: "I agree to the",
      bookTicket: "Book Ticket",
      addPassenger: "Add Passenger",
      passengerNumber: "Passenger #",
      removePassenger: "Remove",
      selectCabinClass: "Select cabin class",
      selectMealPreference: "Select meal preference",
      selectSpecialAssistance: "Select if needed",
      availableVessels: "Available Vessels",
      selectVessel: "Select Vessel",
      vesselDetails: "Vessel Details",
      selectDeparturePort: "Select departure port",
      selectArrivalPort: "Select arrival port",
      departureDatePlaceholder: "Select departure date",
      returnDatePlaceholder: "Select return date (optional)",
      vesselName: "Vessel Name",
      vesselType: "Vessel Type",
      capacity: "Capacity",
      amenities: "Amenities",
      availableCabins: "Available Cabins",
      cabinType: "Cabin Type",
      price: "Price",
      perPerson: "per person",
      facilities: "Facilities",
      viewDetails: "View Details",
      cabinDetails: "Cabin Details",
      bedsCount: "Beds",
      maxOccupancy: "Max Occupancy",
      cabinSize: "Cabin Size",
      squareMeters: "square meters",
      window: "Window",
      privateBalcony: "Private Balcony",
      privateBathroom: "Private Bathroom",
      airConditioning: "Air Conditioning",
      tv: "TV",
      wifi: "WiFi",
      safeDeposit: "Safe Deposit",
      minibar: "Minibar",
      yes: "Yes",
      no: "No",
      bookCabin: "Book this Cabin",
      includesBreakfast: "Includes Breakfast",
      cabinAmenities: "Cabin Amenities",
      vesselAmenities: "Vessel Amenities",
      restaurant: "Restaurant",
      bar: "Bar",
      swimmingPool: "Swimming Pool",
      spa: "Spa",
      gym: "Gym",
      entertainment: "Entertainment",
      medicalService: "Medical Service",
      laundryService: "Laundry Service",
      
      // Services page
      servicesTitle: "Our Services",
      oceansFreight: "Ocean Freight",
      oceanFreightSubtitle: "Full container and consolidation services for global ocean shipping",
      airFreightService: "Air Freight",
      airFreightSubtitle: "Express and standard air cargo services worldwide",
      roadTransportService: "Road Transport",
      roadTransportSubtitle: "Domestic and cross-border road freight solutions",
      warehouseService: "Warehousing",
      warehouseSubtitle: "Secure storage and distribution solutions",
      customsClearanceService: "Customs Clearance",
      customsClearanceSubtitle: "Expert customs brokerage and compliance services",
      courierService: "Courier Service",
      courierSubtitle: "Express package and document delivery services",
      fullContainer: "Full Container Load (FCL)",
      lessThanContainer: "Less Than Container Load (LCL)",
      dangGoodsShipping: "Dangerous Goods Shipping",
      refrigeratedCargo: "Refrigerated Cargo",
      projectCargo: "Project Cargo",
      expressDelivery: "Express Delivery",
      standardAirFreight: "Standard Air Freight",
      charterService: "Charter Service",
      temperatureControlled: "Temperature Controlled",
      hazardousMaterials: "Hazardous Materials",
      truckload: "Full Truckload (FTL)",
      lessTruckload: "Less Than Truckload (LTL)",
      expeditedService: "Expedited Service",
      localDelivery: "Local Delivery",
      crossBorder: "Cross-Border Transport",
      shortTerm: "Short-Term Storage",
      longTerm: "Long-Term Storage",
      distribution: "Distribution Services",
      fulfillment: "Fulfillment Services",
      inventoryManagement: "Inventory Management",
      import: "Import Clearance",
      export: "Export Clearance",
      documentation: "Documentation Services",
      tariffClassification: "Tariff Classification",
      dutyTaxManagement: "Duty & Tax Management",
      sameDay: "Same Day Delivery",
      nextDay: "Next Day Delivery",
      international: "International Courier",
      mailroom: "Mailroom Services",
      handCarry: "Hand Carry Services",
      learnMoreButton: "Learn More",
      requestQuoteButton: "Request Quote",
      serviceFeatures: "Service Features",
      whyChooseUs: "Why Choose Us",
      globalNetwork: "Global Network",
      globalNetworkDesc: "Our extensive network enables seamless shipping across continents",
      advancedTechnology: "Advanced Technology",
      advancedTechDesc: "Blockchain-powered platform for complete transparency and security",
      customerService: "24/7 Customer Service",
      customerServiceDesc: "Round-the-clock support for all your shipping needs",
      competitivePricing: "Competitive Pricing",
      competitivePricingDesc: "Cost-effective solutions without compromising on quality",
      serviceInquiry: "Service Inquiry",
      sendInquiry: "Send Inquiry",
      getQuote: "Get Quote",
      droneDelivery: "Drone Delivery",
      droneSubtitle: "Fast and efficient last-mile delivery using drone technology",
      urbanDelivery: "Urban Delivery",
      ruralAccess: "Rural Access",
      medicalDelivery: "Medical Delivery",
      urgentShipments: "Urgent Shipments",
      audioConsolidation: "Air Consolidation",
      airConsolSubtitle: "Cost-effective groupage services for air freight",
      oceanConsolidation: "Ocean Consolidation",
      oceanConsolSubtitle: "Efficient LCL services for ocean freight",
      
      // Bill of lading
      billOfLading: "Bill of Lading",
      cargo: "Cargo",
      containerNumbers: "Container Numbers",
      shipper: "Shipper",
      consignee: "Consignee",
      notifyParty: "Notify Party",
      placeOfReceipt: "Place of Receipt",
      placeOfLoading: "Place of Loading",
      placeOfDischarge: "Place of Discharge",
      placeOfDelivery: "Place of Delivery",
      marks: "Marks & Numbers",
      goodsDescription: "Goods Description",
      packageCount: "Package Count",
      grossWeight: "Gross Weight",
      measurement: "Measurement",
      freightCharges: "Freight Charges",
      prepaid: "Prepaid",
      collect: "Collect",
      downloadBillOfLading: "Download Bill of Lading",
      viewBillOfLading: "View Bill of Lading",
      
      // Tracking
      delivered: "Delivered",
      inTransit: "In Transit",
      outForDelivery: "Out for Delivery",
      departedFacility: "Departed Facility",
      arrivedAtFacility: "Arrived at Facility",
      customsClearance: "Customs Clearance",
      clearanceDelay: "Clearance Delay",
      trackingNumber: "Tracking Number",
      containers: "Containers",
      unit: "unit",
      paid: "Paid",
      paymentPending: "Payment Pending",
      paymentOverdue: "Payment Overdue",
      referenceVerified: "Verified",
      referenceNotVerified: "Not Verified",
      viewTrackingDetails: "View Tracking Details",
      awaitingPickup: "Awaiting Pickup",
      scheduleChanged: "Schedule Changed",
      weatherDelay: "Weather Delay",
      operationalDelay: "Operational Delay",
      transportDelay: "Transport Delay",
      
      // Suppliers
      supplier: "Supplier",
      supplierName: "Supplier Name",
      supplierContact: "Supplier Contact",
      supplierEmail: "Supplier Email",
      supplierPhone: "Supplier Phone",
      supplierAddress: "Supplier Address",
      paymentTerms: "Payment Terms",
      invoiceNumber: "Invoice Number",
      invoiceDate: "Invoice Date",
      dueDate: "Due Date",
      paymentStatus: "Payment Status",
      makePayment: "Make Payment",
      viewInvoice: "View Invoice",
      downloadInvoice: "Download Invoice",
      servicesProvided: "Services Provided",
      supplierType: "Supplier Type",
      paymentHistory: "Payment History",
      supplierInvoices: "Supplier Invoices",
      supplierDetails: "Supplier Details",
      searchSuppliers: "Search Suppliers",
      addSupplier: "Add Supplier",
      editSupplier: "Edit Supplier",
      deleteSupplier: "Delete Supplier",
      supplierPayment: "Supplier Payment",
      
      // Payment Methods
      creditCard: "Credit Card",
      debitCard: "Debit Card",
      bankTransfer: "Bank Transfer",
      paypal: "PayPal",
      cryptoPayment: "Cryptocurrency Payment",
      mobilePayment: "Mobile Payment",
      cashOnDelivery: "Cash on Delivery",
      enterCardDetails: "Enter your card details",
      enterBankDetails: "Enter your bank details",
      enterPayPalEmail: "Enter your PayPal email",
      enterWalletAddress: "Enter your wallet address",
      enterMobileNumber: "Enter your mobile number"
    },
    fr: {
      // Common
      back: "Retour",
      submit: "Soumettre",
      reset: "Réinitialiser",
      cancel: "Annuler",
      send: "Envoyer",
      error: "Erreur",
      close: "Fermer",
      search: "Rechercher",
      loading: "Chargement...",
      allRightsReserved: "Tous droits réservés",
      
      // Home page
      heroTitle: "Révolutionner le Transport Maritime Global avec la Technologie Blockchain",
      heroSubtitle: "Services de logistique et de transitaire de bout en bout avec une transparence et une efficacité améliorées",
      getStarted: "Commencer",
      learnMore: "En savoir plus",
      trackShipment: "Suivre l'expédition",
      enterTracking: "Entrez le numéro de suivi",
      requestQuote: "Demander un devis",
      calculatePalletPrice: "Calculer le prix de la palette",
      recentShipments: "Expéditions récentes",
      status: "Statut",
      deliveryDate: "Date de livraison",
      origin: "Origine",
      destination: "Destination",
      shippingServices: "Nos services d'expédition",
      oceanFreight: "Fret maritime",
      oceanFreightDescription: "Solutions de fret maritime fiables et rentables pour votre cargo",
      airFreight: "Fret aérien",
      airFreightDescription: "Services de fret aérien rapides et efficaces pour les envois urgents",
      roadTransport: "Transport routier",
      roadTransportDescription: "Solutions de transport routier efficaces pour vos besoins d'expédition nationaux",
      warehousing: "Entreposage",
      warehousingDescription: "Solutions d'entreposage sécurisées et flexibles pour vos besoins de stockage",
      customs: "Dédouanement",
      customsDescription: "Services de dédouanement sans tracas pour vos envois internationaux",
      insurance: "Assurance cargo",
      insuranceDescription: "Assurance cargo complète pour vos envois de valeur",
      trustedBy: "Utilisé par des entreprises leaders dans le monde entier",
      testimonials: "Témoignages",
      testimonialText1: "Eazy Chain a transformé nos opérations logistiques avec leur solution blockchain innovante. Nous avons maintenant une visibilité complète de notre chaîne d'approvisionnement.",
      testimonialAuthor1: "Jean Dupont, Responsable Logistique",
      testimonialText2: "Le niveau de transparence et d'efficacité que fournit Eazy Chain est inégalé. Nous avons réduit nos coûts d'expédition de 20%.",
      testimonialAuthor2: "Sarah Martin, Directrice de la Chaîne d'Approvisionnement",
      testimonialText3: "La plateforme d'Eazy Chain a simplifié notre processus de dédouanement et réduit significativement les retards.",
      testimonialAuthor3: "Michel Brun, Responsable des Opérations",
      aboutUs: "À propos de nous",
      aboutUsText: "Eazy Chain est une plateforme de gestion logistique et de chaîne d'approvisionnement basée sur la blockchain. Nous exploitons une technologie de pointe pour fournir une visibilité de bout en bout, une sécurité renforcée et une efficacité accrue dans le transport maritime mondial.",
      contactUs: "Contactez-nous",
      contactUsText: "Vous avez des questions ou besoin d'assistance? Notre équipe est là pour vous aider avec tous vos besoins d'expédition et de logistique.",
      email: "Email",
      phone: "Téléphone",
      address: "Adresse",
      headquarters: "Siège social",
      sendMessage: "Envoyer un message",
      yourName: "Votre nom",
      yourEmail: "Votre email",
      subject: "Sujet",
      message: "Message",
      
      // Footer
      followUs: "Suivez-nous",
      newsletter: "Newsletter",
      subscribeText: "Abonnez-vous à notre newsletter pour les dernières mises à jour",
      subscribe: "S'abonner",
      termsOfService: "Conditions d'utilisation",
      privacyPolicy: "Politique de confidentialité",
      
      // Navigation
      home: "Accueil",
      services: "Services",
      booking: "Réservation",
      tracking: "Suivi",
      passengers: "Passagers",
      payment: "Paiement",
      account: "Compte",
      login: "Connexion",
      logout: "Déconnexion",
      register: "S'inscrire",
      dashboard: "Tableau de bord",
      
      // Booking page
      bookingTitle: "Réservez votre expédition",
      bookingSubtitle: "Remplissez le formulaire ci-dessous pour réserver votre expédition",
      shipmentDetails: "Détails de l'expédition",
      freightType: "Type de fret",
      containerCount: "Nombre de conteneurs",
      cargoType: "Type de cargo",
      cargoDescription: "Description du cargo",
      weight: "Poids (kg)",
      dimensions: "Dimensions (cm)",
      palletCount: "Nombre de palettes",
      palletType: "Type de palette",
      specialRequirements: "Exigences spéciales",
      pickupDetails: "Détails du ramassage",
      pickupDate: "Date de ramassage",
      pickupTime: "Heure de ramassage",
      pickupAddress: "Adresse de ramassage",
      deliveryDetails: "Détails de livraison",
      deliveryDate: "Date de livraison",
      deliveryTime: "Heure de livraison",
      deliveryAddress: "Adresse de livraison",
      contactDetails: "Coordonnées",
      contactName: "Nom du contact",
      contactEmail: "Email du contact",
      contactPhone: "Téléphone du contact",
      companyName: "Nom de l'entreprise",
      bookNow: "Réserver maintenant",
      bookingReference: "Référence de réservation",
      estimatedCost: "Coût estimé",
      termsAgreement: "J'accepte les termes et conditions",
      selectFreightType: "Sélectionnez le type de fret",
      selectCargoType: "Sélectionnez le type de cargo",
      selectPalletType: "Sélectionnez le type de palette",
      enterCargoDescription: "Entrez la description du cargo",
      enterPickupAddress: "Entrez l'adresse de ramassage",
      enterDeliveryAddress: "Entrez l'adresse de livraison",
      fullName: "Nom complet",
      emailPlaceholder: "nom@exemple.com",
      phonePlaceholder: "+33 (0)6 00 00 00 00",
      enterCompanyName: "Entrez le nom de l'entreprise",
      needPickupService: "J'ai besoin d'un service de ramassage",
      checkBoxIfPickupNeeded: "Cochez cette case si vous avez besoin que nous ramassions votre cargo",
      bookingConfirmed: "Réservation confirmée !",
      originPort: "Port d'origine",
      destinationPort: "Port de destination",
      bookingRequestSubmitted: "Demande de réservation soumise !",
      bookingConfirmation: "Merci pour votre demande de réservation. Vous recevrez un email de confirmation sous peu.",
      selectOriginPort: "Sélectionnez le port d'origine",
      selectDestinationPort: "Sélectionnez le port de destination",
      departureDate: "Date de départ",
      selectDepartureDate: "Sélectionnez la date de départ",
      noDescriptionFound: "Aucune description trouvée",
      yourBookingReference: "Votre référence de réservation",
      keepReferenceForPaymentTracking: "Veuillez conserver cette référence pour le paiement et le suivi",
      selectCargoDescription: "Sélectionnez la description du cargo",
      scanQrCodeForPayment: "Scannez le code QR pour le paiement",
      payNow: "Payer maintenant",
      newBooking: "Nouvelle réservation",
      submitting: "Soumission en cours...",
      submitBookingRequest: "Soumettre la demande de réservation",
      
      // Tracking page
      trackingTitle: "Suivez votre expédition",
      trackingSubtitle: "Entrez votre numéro de suivi pour voir le statut de votre expédition",
      trackButton: "Suivre",
      trackingNumber: "Numéro de suivi",
      enterTrackingNumber: "Entrez le numéro de suivi",
      shipmentNotFound: "Expédition non trouvée",
      shipmentDetails: "Détails de l'expédition",
      currentStatus: "Statut actuel",
      statusHistory: "Historique du statut",
      statusDate: "Date",
      statusLocation: "Emplacement",
      statusDetails: "Détails",
      latestUpdate: "Dernière mise à jour",
      estimatedArrival: "Arrivée estimée",
      departurePort: "Port de départ",
      arrivalPort: "Port d'arrivée",
      transitTime: "Temps de transit",
      days: "jours",
      documentType: "Type de document",
      documentNumber: "Numéro de document",
      vessel: "Navire",
      voyage: "Voyage",
      
      // Payment page
      paymentTitle: "Paiement",
      securePayment: "Paiement sécurisé",
      paymentDesc: "Complétez votre paiement en toute sécurité pour confirmer votre réservation",
      paymentDetails: "Détails du paiement",
      bookingId: "ID de réservation",
      amount: "Montant",
      currency: "Devise",
      paymentMethod: "Méthode de paiement",
      cardNumber: "Numéro de carte",
      cardholderName: "Nom du titulaire",
      expiryDate: "Date d'expiration",
      cvv: "CVV",
      billingAddress: "Adresse de facturation",
      city: "Ville",
      country: "Pays",
      postalCode: "Code postal",
      pay: "Payer",
      processing: "Traitement en cours...",
      paymentSuccessful: "Paiement réussi !",
      paymentFailed: "Paiement échoué !",
      tryAgain: "Veuillez réessayer ou utiliser une autre méthode de paiement.",
      backToBooking: "Retour à la réservation",
      transactionId: "ID de transaction",
      transactionDate: "Date de transaction",
      shipmentId: "ID d'expédition",
      description: "Description",
      weight: "Poids",
      units: "unités",
      costBreakdown: "Détail des coûts",
      freightCost: "Coût de fret",
      handlingFees: "Frais de manutention",
      documentation: "Documentation",
      insurance: "Assurance",
      totalAmount: "Montant total",
      estimatedDelivery: "Livraison estimée",
      loadingPayment: "Chargement des détails de paiement...",
      verifyBookingReference: "Vérifier la référence de réservation",
      enterBookingReference: "Entrez votre référence de réservation",
      verify: "Vérifier",
      verifying: "Vérification en cours...",
      verified: "Vérifié",
      referenceVerificationFailed: "La vérification de la référence de réservation a échoué",
      referenceNotFound: "Référence de réservation non trouvée",
      invalidReference: "Référence de réservation invalide",
      
      // Passenger booking page
      passengerBookingTitle: "Réservation de passager",
      passengerDetails: "Détails du passager",
      travelDetails: "Détails du voyage",
      personalInformation: "Informations personnelles",
      firstName: "Prénom",
      lastName: "Nom",
      dateOfBirth: "Date de naissance",
      nationality: "Nationalité",
      passportNumber: "Numéro de passeport",
      passportExpiry: "Date d'expiration du passeport",
      departurePort: "Port de départ",
      arrivalPort: "Port d'arrivée",
      departureDate: "Date de départ",
      returnDate: "Date de retour (Optionnel)",
      adults: "Adultes",
      children: "Enfants",
      infants: "Bébés",
      cabinClass: "Classe de cabine",
      economy: "Économique",
      business: "Affaires",
      firstClass: "Première classe",
      mealPreference: "Préférence de repas",
      standard: "Standard",
      vegetarian: "Végétarien",
      vegan: "Végétalien",
      glutenFree: "Sans gluten",
      kosher: "Casher",
      halal: "Halal",
      specialAssistance: "Assistance spéciale",
      wheelchair: "Fauteuil roulant",
      visualAssistance: "Assistance visuelle",
      hearingAssistance: "Assistance auditive",
      none: "Aucune",
      emergencyContact: "Contact d'urgence",
      relationship: "Relation",
      totalCost: "Coût total",
      termsAndConditions: "Termes et conditions",
      iAgree: "J'accepte les",
      bookTicket: "Réserver le billet",
      addPassenger: "Ajouter un passager",
      passengerNumber: "Passager #",
      removePassenger: "Supprimer",
      selectCabinClass: "Sélectionnez la classe de cabine",
      selectMealPreference: "Sélectionnez la préférence de repas",
      selectSpecialAssistance: "Sélectionnez si nécessaire",
      availableVessels: "Navires disponibles",
      selectVessel: "Sélectionner un navire",
      vesselDetails: "Détails du navire",
      selectDeparturePort: "Sélectionnez le port de départ",
      selectArrivalPort: "Sélectionnez le port d'arrivée",
      departureDatePlaceholder: "Sélectionnez la date de départ",
      returnDatePlaceholder: "Sélectionnez la date de retour (optionnel)",
      vesselName: "Nom du navire",
      vesselType: "Type de navire",
      capacity: "Capacité",
      amenities: "Commodités",
      availableCabins: "Cabines disponibles",
      cabinType: "Type de cabine",
      price: "Prix",
      perPerson: "par personne",
      facilities: "Installations",
      viewDetails: "Voir les détails",
      cabinDetails: "Détails de la cabine",
      bedsCount: "Lits",
      maxOccupancy: "Occupation maximale",
      cabinSize: "Taille de la cabine",
      squareMeters: "mètres carrés",
      window: "Fenêtre",
      privateBalcony: "Balcon privé",
      privateBathroom: "Salle de bain privée",
      airConditioning: "Climatisation",
      tv: "Télévision",
      wifi: "WiFi",
      safeDeposit: "Coffre-fort",
      minibar: "Minibar",
      yes: "Oui",
      no: "Non",
      bookCabin: "Réserver cette cabine",
      includesBreakfast: "Petit-déjeuner inclus",
      cabinAmenities: "Commodités de la cabine",
      vesselAmenities: "Commodités du navire",
      restaurant: "Restaurant",
      bar: "Bar",
      swimmingPool: "Piscine",
      spa: "Spa",
      gym: "Salle de sport",
      entertainment: "Divertissement",
      medicalService: "Service médical",
      laundryService: "Service de blanchisserie",
      
      // Services page
      servicesTitle: "Nos services",
      oceansFreight: "Fret maritime",
      oceanFreightSubtitle: "Services de conteneur complet et de groupage pour le transport maritime mondial",
      airFreightService: "Fret aérien",
      airFreightSubtitle: "Services de fret aérien express et standard dans le monde entier",
      roadTransportService: "Transport routier",
      roadTransportSubtitle: "Solutions de fret routier nationales et transfrontalières",
      warehouseService: "Entreposage",
      warehouseSubtitle: "Solutions de stockage et de distribution sécurisées",
      customsClearanceService: "Dédouanement",
      customsClearanceSubtitle: "Services experts de courtage en douane et de conformité",
      courierService: "Service de messagerie",
      courierSubtitle: "Services de livraison express de colis et de documents",
      fullContainer: "Conteneur complet (FCL)",
      lessThanContainer: "Conteneur partiel (LCL)",
      dangGoodsShipping: "Expédition de marchandises dangereuses",
      refrigeratedCargo: "Cargo réfrigéré",
      projectCargo: "Cargo de projet",
      expressDelivery: "Livraison express",
      standardAirFreight: "Fret aérien standard",
      charterService: "Service d'affrètement",
      temperatureControlled: "Contrôlé en température",
      hazardousMaterials: "Matières dangereuses",
      truckload: "Camion complet (FTL)",
      lessTruckload: "Camion partiel (LTL)",
      expeditedService: "Service accéléré",
      localDelivery: "Livraison locale",
      crossBorder: "Transport transfrontalier",
      shortTerm: "Stockage à court terme",
      longTerm: "Stockage à long terme",
      distribution: "Services de distribution",
      fulfillment: "Services de fulfillment",
      inventoryManagement: "Gestion des stocks",
      import: "Dédouanement à l'importation",
      export: "Dédouanement à l'exportation",
      documentation: "Services de documentation",
      tariffClassification: "Classification tarifaire",
      dutyTaxManagement: "Gestion des droits et taxes",
      sameDay: "Livraison le jour même",
      nextDay: "Livraison le lendemain",
      international: "Messagerie internationale",
      mailroom: "Services de salle de courrier",
      handCarry: "Services de transport à la main",
      learnMoreButton: "En savoir plus",
      requestQuoteButton: "Demander un devis",
      serviceFeatures: "Caractéristiques du service",
      whyChooseUs: "Pourquoi nous choisir",
      globalNetwork: "Réseau mondial",
      globalNetworkDesc: "Notre vaste réseau permet une expédition sans faille entre les continents",
      advancedTechnology: "Technologie avancée",
      advancedTechDesc: "Plateforme basée sur la blockchain pour une transparence et une sécurité complètes",
      customerService: "Service client 24/7",
      customerServiceDesc: "Support permanent pour tous vos besoins d'expédition",
      competitivePricing: "Prix compétitifs",
      competitivePricingDesc: "Solutions rentables sans compromis sur la qualité",
      serviceInquiry: "Demande de service",
      sendInquiry: "Envoyer une demande",
      getQuote: "Obtenir un devis",
      droneDelivery: "Livraison par drone",
      droneSubtitle: "Livraison du dernier kilomètre rapide et efficace utilisant la technologie des drones",
      urbanDelivery: "Livraison urbaine",
      ruralAccess: "Accès rural",
      medicalDelivery: "Livraison médicale",
      urgentShipments: "Envois urgents",
      audioConsolidation: "Consolidation aérienne",
      airConsolSubtitle: "Services de groupage rentables pour le fret aérien",
      oceanConsolidation: "Consolidation maritime",
      oceanConsolSubtitle: "Services LCL efficaces pour le fret maritime",
      
      // Bill of lading
      billOfLading: "Connaissement",
      cargo: "Cargo",
      containerNumbers: "Numéros de conteneur",
      shipper: "Expéditeur",
      consignee: "Destinataire",
      notifyParty: "Partie à notifier",
      placeOfReceipt: "Lieu de réception",
      placeOfLoading: "Lieu de chargement",
      placeOfDischarge: "Lieu de déchargement",
      placeOfDelivery: "Lieu de livraison",
      marks: "Marques et numéros",
      goodsDescription: "Description des marchandises",
      packageCount: "Nombre de colis",
      grossWeight: "Poids brut",
      measurement: "Mesure",
      freightCharges: "Frais de fret",
      prepaid: "Prépayé",
      collect: "À percevoir",
      downloadBillOfLading: "Télécharger le connaissement",
      viewBillOfLading: "Voir le connaissement",
      
      // Tracking
      delivered: "Livré",
      inTransit: "En transit",
      outForDelivery: "En cours de livraison",
      departedFacility: "Départ de l'installation",
      arrivedAtFacility: "Arrivée à l'installation",
      customsClearance: "Dédouanement",
      clearanceDelay: "Retard de dédouanement",
      paid: "Payé",
      paymentPending: "Paiement en attente",
      paymentOverdue: "Paiement en retard",
      referenceVerified: "Vérifié",
      referenceNotVerified: "Non vérifié",
      viewTrackingDetails: "Voir les détails de suivi",
      awaitingPickup: "En attente de ramassage",
      scheduleChanged: "Horaire modifié",
      weatherDelay: "Retard météorologique",
      operationalDelay: "Retard opérationnel",
      transportDelay: "Retard de transport",
      
      // Suppliers
      supplier: "Fournisseur",
      supplierName: "Nom du fournisseur",
      supplierContact: "Contact du fournisseur",
      supplierEmail: "Email du fournisseur",
      supplierPhone: "Téléphone du fournisseur",
      supplierAddress: "Adresse du fournisseur",
      paymentTerms: "Conditions de paiement",
      invoiceNumber: "Numéro de facture",
      invoiceDate: "Date de facture",
      dueDate: "Date d'échéance",
      paymentStatus: "Statut du paiement",
      makePayment: "Effectuer un paiement",
      viewInvoice: "Voir la facture",
      downloadInvoice: "Télécharger la facture",
      servicesProvided: "Services fournis",
      supplierType: "Type de fournisseur",
      paymentHistory: "Historique des paiements",
      supplierInvoices: "Factures du fournisseur",
      supplierDetails: "Détails du fournisseur",
      searchSuppliers: "Rechercher des fournisseurs",
      addSupplier: "Ajouter un fournisseur",
      editSupplier: "Modifier un fournisseur",
      deleteSupplier: "Supprimer un fournisseur",
      supplierPayment: "Paiement du fournisseur",
      
      // Payment Methods
      creditCard: "Carte de crédit",
      debitCard: "Carte de débit",
      bankTransfer: "Virement bancaire",
      paypal: "PayPal",
      cryptoPayment: "Paiement en cryptomonnaie",
      mobilePayment: "Paiement mobile",
      cashOnDelivery: "Paiement à la livraison",
      enterCardDetails: "Entrez les détails de votre carte",
      enterBankDetails: "Entrez vos coordonnées bancaires",
      enterPayPalEmail: "Entrez votre email PayPal",
      enterWalletAddress: "Entrez l'adresse de votre portefeuille",
      enterMobileNumber: "Entrez votre numéro de mobile"
    },
    es: {
      // Common
      back: "Atrás",
      submit: "Enviar",
      reset: "Restablecer",
      cancel: "Cancelar",
      send: "Enviar",
      error: "Error",
      close: "Cerrar",
      search: "Buscar",
      loading: "Cargando...",
      allRightsReserved: "Todos los derechos reservados",
      
      // Home page
      heroTitle: "Revolucionando el Transporte Marítimo Global con Tecnología Blockchain",
      heroSubtitle: "Servicios de logística y transporte de carga de extremo a extremo con mayor transparencia y eficiencia",
      getStarted: "Comenzar",
      learnMore: "Más información",
      trackShipment: "Rastrear envío",
      enterTracking: "Ingrese número de seguimiento",
      requestQuote: "Solicitar cotización",
      calculatePalletPrice: "Calcular precio de palet",
      recentShipments: "Envíos recientes",
      status: "Estado",
      deliveryDate: "Fecha de entrega",
      origin: "Origen",
      destination: "Destino",
      shippingServices: "Nuestros Servicios de Envío",
      oceanFreight: "Flete marítimo",
      oceanFreightDescription: "Soluciones de flete marítimo confiables y rentables para su carga",
      airFreight: "Flete aéreo",
      airFreightDescription: "Servicios de flete aéreo rápidos y eficientes para envíos urgentes",
      roadTransport: "Transporte terrestre",
      roadTransportDescription: "Soluciones eficientes de transporte terrestre para sus necesidades de envío nacional",
      warehousing: "Almacenamiento",
      warehousingDescription: "Soluciones de almacenamiento seguras y flexibles para sus necesidades de almacenamiento",
      customs: "Despacho de aduanas",
      customsDescription: "Servicios de despacho de aduanas sin complicaciones para sus envíos internacionales",
      insurance: "Seguro de carga",
      insuranceDescription: "Seguro de carga integral para sus envíos valiosos",
      trustedBy: "Confiado por empresas líderes en todo el mundo",
      testimonials: "Testimonios",
      testimonialText1: "Eazy Chain ha transformado nuestras operaciones logísticas con su innovadora solución blockchain. Ahora tenemos visibilidad completa de nuestra cadena de suministro.",
      testimonialAuthor1: "Juan Pérez, Gerente de Logística",
      testimonialText2: "El nivel de transparencia y eficiencia que proporciona Eazy Chain es inigualable. Hemos reducido nuestros costos de envío en un 20%.",
      testimonialAuthor2: "Sara Rodríguez, Directora de Cadena de Suministro",
      testimonialText3: "La plataforma de Eazy Chain ha simplificado nuestro proceso de despacho de aduanas y reducido significativamente los retrasos.",
      testimonialAuthor3: "Miguel Moreno, Gerente de Operaciones",
      aboutUs: "Sobre nosotros",
      aboutUsText: "Eazy Chain es una plataforma líder de gestión logística y de cadena de suministro basada en blockchain. Aprovechamos tecnología de vanguardia para proporcionar visibilidad de extremo a extremo, seguridad mejorada y mayor eficiencia en el envío global.",
      contactUs: "Contáctenos",
      contactUsText: "¿Tiene preguntas o necesita asistencia? Nuestro equipo está aquí para ayudarlo con todas sus necesidades de envío y logística.",
      email: "Correo electrónico",
      phone: "Teléfono",
      address: "Dirección",
      headquarters: "Sede central",
      sendMessage: "Enviar mensaje",
      yourName: "Su nombre",
      yourEmail: "Su correo electrónico",
      subject: "Asunto",
      message: "Mensaje",
      
      // Footer
      followUs: "Síganos",
      newsletter: "Boletín informativo",
      subscribeText: "Suscríbase a nuestro boletín para recibir las últimas actualizaciones",
      subscribe: "Suscribirse",
      termsOfService: "Términos de servicio",
      privacyPolicy: "Política de privacidad",
      
      // Navigation
      home: "Inicio",
      services: "Servicios",
      booking: "Reservas",
      tracking: "Seguimiento",
      passengers: "Pasajeros",
      payment: "Pago",
      account: "Cuenta",
      login: "Iniciar sesión",
      logout: "Cerrar sesión",
      register: "Registrarse",
      dashboard: "Panel de control",
      
      // Booking page
      bookingTitle: "Reserve su envío",
      bookingSubtitle: "Complete el formulario a continuación para reservar su envío",
      shipmentDetails: "Detalles del envío",
      freightType: "Tipo de flete",
      containerCount: "Número de contenedores",
      cargoType: "Tipo de carga",
      cargoDescription: "Descripción de la carga",
      weight: "Peso (kg)",
      dimensions: "Dimensiones (cm)",
      palletCount: "Número de palets",
      palletType: "Tipo de palet",
      specialRequirements: "Requisitos especiales",
      pickupDetails: "Detalles de recogida",
      pickupDate: "Fecha de recogida",
      pickupTime: "Hora de recogida",
      pickupAddress: "Dirección de recogida",
      deliveryDetails: "Detalles de entrega",
      deliveryDate: "Fecha de entrega",
      deliveryTime: "Hora de entrega",
      deliveryAddress: "Dirección de entrega",
      contactDetails: "Datos de contacto",
      contactName: "Nombre de contacto",
      contactEmail: "Correo electrónico de contacto",
      contactPhone: "Teléfono de contacto",
      companyName: "Nombre de la empresa",
      bookNow: "Reservar ahora",
      bookingReference: "Referencia de reserva",
      estimatedCost: "Costo estimado",
      termsAgreement: "Acepto los términos y condiciones",
      selectFreightType: "Seleccione tipo de flete",
      selectCargoType: "Seleccione tipo de carga",
      selectPalletType: "Seleccione tipo de palet",
      enterCargoDescription: "Introduzca descripción de la carga",
      enterPickupAddress: "Introduzca dirección de recogida",
      enterDeliveryAddress: "Introduzca dirección de entrega",
      fullName: "Nombre completo",
      emailPlaceholder: "nombre@ejemplo.com",
      phonePlaceholder: "+34 600 000 000",
      enterCompanyName: "Introduzca nombre de la empresa",
      needPickupService: "Necesito servicio de recogida",
      checkBoxIfPickupNeeded: "Marque esta casilla si necesita que recojamos su carga",
      bookingConfirmed: "¡Reserva confirmada!",
      originPort: "Puerto de origen",
      destinationPort: "Puerto de destino",
      bookingRequestSubmitted: "¡Solicitud de reserva enviada!",
      bookingConfirmation: "Gracias por su solicitud de reserva. Recibirá un correo electrónico de confirmación en breve.",
      selectOriginPort: "Seleccione puerto de origen",
      selectDestinationPort: "Seleccione puerto de destino",
      departureDate: "Fecha de salida",
      selectDepartureDate: "Seleccione fecha de salida",
      noDescriptionFound: "No se encontró descripción",
      yourBookingReference: "Su referencia de reserva",
      keepReferenceForPaymentTracking: "Por favor guarde esta referencia para el pago y seguimiento",
      selectCargoDescription: "Seleccione descripción de la carga",
      scanQrCodeForPayment: "Escanee el código QR para el pago",
      payNow: "Pagar ahora",
      newBooking: "Nueva reserva",
      submitting: "Enviando...",
      submitBookingRequest: "Enviar solicitud de reserva",
      
      // Tracking page
      trackingTitle: "Rastrear su envío",
      trackingSubtitle: "Introduzca su número de seguimiento para ver el estado de su envío",
      trackButton: "Rastrear",
      trackingNumber: "Número de seguimiento",
      enterTrackingNumber: "Introduzca número de seguimiento",
      shipmentNotFound: "Envío no encontrado",
      shipmentDetails: "Detalles del envío",
      currentStatus: "Estado actual",
      statusHistory: "Historial de estado",
      statusDate: "Fecha",
      statusLocation: "Ubicación",
      statusDetails: "Detalles",
      latestUpdate: "Última actualización",
      estimatedArrival: "Llegada estimada",
      departurePort: "Puerto de salida",
      arrivalPort: "Puerto de llegada",
      transitTime: "Tiempo de tránsito",
      days: "días",
      documentType: "Tipo de documento",
      documentNumber: "Número de documento",
      vessel: "Buque",
      voyage: "Viaje",
      
      // Payment page
      paymentTitle: "Pago",
      securePayment: "Pago seguro",
      paymentDesc: "Complete su pago de forma segura para confirmar su reserva",
      paymentDetails: "Detalles del pago",
      bookingId: "ID de reserva",
      amount: "Importe",
      currency: "Moneda",
      paymentMethod: "Método de pago",
      cardNumber: "Número de tarjeta",
      cardholderName: "Nombre del titular",
      expiryDate: "Fecha de caducidad",
      cvv: "CVV",
      billingAddress: "Dirección de facturación",
      city: "Ciudad",
      country: "País",
      postalCode: "Código postal",
      pay: "Pagar",
      processing: "Procesando...",
      paymentSuccessful: "¡Pago exitoso!",
      paymentFailed: "¡Pago fallido!",
      tryAgain: "Intente nuevamente o use un método de pago diferente.",
      backToBooking: "Volver a Reservas",
      transactionId: "ID de transacción",
      transactionDate: "Fecha de transacción",
      shipmentId: "ID de envío",
      description: "Descripción",
      weight: "Peso",
      units: "unidades",
      costBreakdown: "Desglose de costos",
      freightCost: "Costo de flete",
      handlingFees: "Tarifas de manipulación",
      documentation: "Documentación",
      insurance: "Seguro",
      totalAmount: "Importe total",
      estimatedDelivery: "Entrega estimada",
      loadingPayment: "Cargando detalles de pago...",
      verifyBookingReference: "Verificar referencia de reserva",
      enterBookingReference: "Introduzca su referencia de reserva",
      verify: "Verificar",
      verifying: "Verificando...",
      verified: "Verificado",
      referenceVerificationFailed: "Verificación de referencia de reserva fallida",
      referenceNotFound: "Referencia de reserva no encontrada",
      invalidReference: "Referencia de reserva inválida",
      
      // Passenger booking page
      passengerBookingTitle: "Reserva de pasajeros",
      passengerDetails: "Detalles del pasajero",
      travelDetails: "Detalles del viaje",
      personalInformation: "Información personal",
      firstName: "Nombre",
      lastName: "Apellido",
      dateOfBirth: "Fecha de nacimiento",
      nationality: "Nacionalidad",
      passportNumber: "Número de pasaporte",
      passportExpiry: "Fecha de caducidad del pasaporte",
      departurePort: "Puerto de salida",
      arrivalPort: "Puerto de llegada",
      departureDate: "Fecha de salida",
      returnDate: "Fecha de regreso (Opcional)",
      adults: "Adultos",
      children: "Niños",
      infants: "Bebés",
      cabinClass: "Clase de cabina",
      economy: "Económica",
      business: "Negocios",
      firstClass: "Primera clase",
      mealPreference: "Preferencia de comida",
      standard: "Estándar",
      vegetarian: "Vegetariana",
      vegan: "Vegana",
      glutenFree: "Sin gluten",
      kosher: "Kosher",
      halal: "Halal",
      specialAssistance: "Asistencia especial",
      wheelchair: "Silla de ruedas",
      visualAssistance: "Asistencia visual",
      hearingAssistance: "Asistencia auditiva",
      none: "Ninguna",
      emergencyContact: "Contacto de emergencia",
      relationship: "Relación",
      totalCost: "Costo total",
      termsAndConditions: "Términos y condiciones",
      iAgree: "Estoy de acuerdo con los",
      bookTicket: "Reservar billete",
      addPassenger: "Añadir pasajero",
      passengerNumber: "Pasajero #",
      removePassenger: "Eliminar",
      selectCabinClass: "Seleccione clase de cabina",
      selectMealPreference: "Seleccione preferencia de comida",
      selectSpecialAssistance: "Seleccione si es necesario",
      availableVessels: "Buques disponibles",
      selectVessel: "Seleccionar buque",
      vesselDetails: "Detalles del buque",
      selectDeparturePort: "Seleccione puerto de salida",
      selectArrivalPort: "Seleccione puerto de llegada",
      departureDatePlaceholder: "Seleccione fecha de salida",
      returnDatePlaceholder: "Seleccione fecha de regreso (opcional)",
      vesselName: "Nombre del buque",
      vesselType: "Tipo de buque",
      capacity: "Capacidad",
      amenities: "Comodidades",
      availableCabins: "Cabinas disponibles",
      cabinType: "Tipo de cabina",
      price: "Precio",
      perPerson: "por persona",
      facilities: "Instalaciones",
      viewDetails: "Ver detalles",
      cabinDetails: "Detalles de la cabina",
      bedsCount: "Camas",
      maxOccupancy: "Ocupación máxima",
      cabinSize: "Tamaño de la cabina",
      squareMeters: "metros cuadrados",
      window: "Ventana",
      privateBalcony: "Balcón privado",
      privateBathroom: "Baño privado",
      airConditioning: "Aire acondicionado",
      tv: "TV",
      wifi: "WiFi",
      safeDeposit: "Caja fuerte",
      minibar: "Minibar",
      yes: "Sí",
      no: "No",
      bookCabin: "Reservar esta cabina",
      includesBreakfast: "Incluye desayuno",
      cabinAmenities: "Comodidades de la cabina",
      vesselAmenities: "Comodidades del buque",
      restaurant: "Restaurante",
      bar: "Bar",
      swimmingPool: "Piscina",
      spa: "Spa",
      gym: "Gimnasio",
      entertainment: "Entretenimiento",
      medicalService: "Servicio médico",
      laundryService: "Servicio de lavandería",
      
      // Services page
      servicesTitle: "Nuestros servicios",
      oceansFreight: "Flete marítimo",
      oceanFreightSubtitle: "Servicios de contenedor completo y consolidación para envíos marítimos globales",
      airFreightService: "Flete aéreo",
      airFreightSubtitle: "Servicios de carga aérea express y estándar en todo el mundo",
      roadTransportService: "Transporte terrestre",
      roadTransportSubtitle: "Soluciones de transporte terrestre nacional y transfronterizo",
      warehouseService: "Almacenamiento",
      warehouseSubtitle: "Soluciones seguras de almacenamiento y distribución",
      customsClearanceService: "Despacho de aduanas",
      customsClearanceSubtitle: "Servicios expertos de agente de aduanas y cumplimiento",
      courierService: "Servicio de mensajería",
      courierSubtitle: "Servicios express de entrega de paquetes y documentos",
      fullContainer: "Carga de contenedor completo (FCL)",
      lessThanContainer: "Carga de contenedor parcial (LCL)",
      dangGoodsShipping: "Envío de mercancías peligrosas",
      refrigeratedCargo: "Carga refrigerada",
      projectCargo: "Carga de proyecto",
      expressDelivery: "Entrega express",
      standardAirFreight: "Flete aéreo estándar",
      charterService: "Servicio de flete",
      temperatureControlled: "Control de temperatura",
      hazardousMaterials: "Materiales peligrosos",
      truckload: "Carga completa (FTL)",
      lessTruckload: "Carga parcial (LTL)",
      expeditedService: "Servicio acelerado",
      localDelivery: "Entrega local",
      crossBorder: "Transporte transfronterizo",
      shortTerm: "Almacenamiento a corto plazo",
      longTerm: "Almacenamiento a largo plazo",
      distribution: "Servicios de distribución",
      fulfillment: "Servicios de fulfillment",
      inventoryManagement: "Gestión de inventario",
      import: "Despacho de importación",
      export: "Despacho de exportación",
      documentation: "Servicios de documentación",
      tariffClassification: "Clasificación arancelaria",
      dutyTaxManagement: "Gestión de aranceles e impuestos",
      sameDay: "Entrega el mismo día",
      nextDay: "Entrega al día siguiente",
      international: "Mensajería internacional",
      mailroom: "Servicios de sala de correo",
      handCarry: "Servicios de transporte manual",
      learnMoreButton: "Más información",
      requestQuoteButton: "Solicitar cotización",
      serviceFeatures: "Características del servicio",
      whyChooseUs: "Por qué elegirnos",
      globalNetwork: "Red global",
      globalNetworkDesc: "Nuestra extensa red permite envíos sin problemas entre continentes",
      advancedTechnology: "Tecnología avanzada",
      advancedTechDesc: "Plataforma basada en blockchain para total transparencia y seguridad",
      customerService: "Servicio al cliente 24/7",
      customerServiceDesc: "Soporte permanente para todas sus necesidades de envío",
      competitivePricing: "Precios competitivos",
      competitivePricingDesc: "Soluciones rentables sin comprometer la calidad",
      serviceInquiry: "Consulta de servicio",
      sendInquiry: "Enviar consulta",
      getQuote: "Obtener cotización",
      droneDelivery: "Entrega por dron",
      droneSubtitle: "Entrega de última milla rápida y eficiente utilizando tecnología de drones",
      urbanDelivery: "Entrega urbana",
      ruralAccess: "Acceso rural",
      medicalDelivery: "Entrega médica",
      urgentShipments: "Envíos urgentes",
      audioConsolidation: "Consolidación aérea",
      airConsolSubtitle: "Servicios rentables de agrupación para flete aéreo",
      oceanConsolidation: "Consolidación marítima",
      oceanConsolSubtitle: "Servicios LCL eficientes para flete marítimo",
      
      // Bill of lading
      billOfLading: "Conocimiento de embarque",
      cargo: "Carga",
      containerNumbers: "Números de contenedor",
      shipper: "Remitente",
      consignee: "Destinatario",
      notifyParty: "Parte a notificar",
      placeOfReceipt: "Lugar de recepción",
      placeOfLoading: "Lugar de carga",
      placeOfDischarge: "Lugar de descarga",
      placeOfDelivery: "Lugar de entrega",
      marks: "Marcas y números",
      goodsDescription: "Descripción de mercancías",
      packageCount: "Número de bultos",
      grossWeight: "Peso bruto",
      measurement: "Medidas",
      freightCharges: "Cargos de flete",
      prepaid: "Prepagado",
      collect: "Por cobrar",
      downloadBillOfLading: "Descargar conocimiento de embarque",
      viewBillOfLading: "Ver conocimiento de embarque",
      
      // Tracking
      delivered: "Entregado",
      inTransit: "En tránsito",
      outForDelivery: "En reparto",
      departedFacility: "Salida de instalación",
      arrivedAtFacility: "Llegada a instalación",
      customsClearance: "Despacho de aduanas",
      clearanceDelay: "Retraso en despacho",
      paid: "Pagado",
      paymentPending: "Pago Pendiente",
      paymentOverdue: "Pago Atrasado",
      referenceVerified: "Verificado",
      referenceNotVerified: "No verificado",
      viewTrackingDetails: "Ver detalles de seguimiento",
      awaitingPickup: "Esperando recogida",
      scheduleChanged: "Horario cambiado",
      weatherDelay: "Retraso por clima",
      operationalDelay: "Retraso operativo",
      transportDelay: "Retraso de transporte",
      
      // Suppliers
      supplier: "Proveedor",
      supplierName: "Nombre del proveedor",
      supplierContact: "Contacto del proveedor",
      supplierEmail: "Correo del proveedor",
      supplierPhone: "Teléfono del proveedor",
      supplierAddress: "Dirección del proveedor",
      paymentTerms: "Condiciones de pago",
      invoiceNumber: "Número de factura",
      invoiceDate: "Fecha de factura",
      dueDate: "Fecha de vencimiento",
      paymentStatus: "Estado del pago",
      makePayment: "Realizar pago",
      viewInvoice: "Ver factura",
      downloadInvoice: "Descargar factura",
      servicesProvided: "Servicios proporcionados",
      supplierType: "Tipo de proveedor",
      paymentHistory: "Historial de pagos",
      supplierInvoices: "Facturas del proveedor",
      supplierDetails: "Detalles del proveedor",
      searchSuppliers: "Buscar proveedores",
      addSupplier: "Añadir proveedor",
      editSupplier: "Editar proveedor",
      deleteSupplier: "Eliminar proveedor",
      supplierPayment: "Pago a proveedor",
      
      // Payment Methods
      creditCard: "Tarjeta de crédito",
      debitCard: "Tarjeta de débito",
      bankTransfer: "Transferencia bancaria",
      paypal: "PayPal",
      cryptoPayment: "Pago con criptomoneda",
      mobilePayment: "Pago móvil",
      cashOnDelivery: "Pago contra entrega",
      enterCardDetails: "Ingrese los detalles de su tarjeta",
      enterBankDetails: "Ingrese sus datos bancarios",
      enterPayPalEmail: "Ingrese su correo de PayPal",
      enterWalletAddress: "Ingrese la dirección de su billetera",
      enterMobileNumber: "Ingrese su número móvil"
    }
  };

  const t = (key: string): string => {
    if (!translations[language]) {
      return key;
    }
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
