import React, { createContext, useState, useContext, useCallback } from 'react';

interface LanguageContextProps {
  language: string;
  t: (key: string, params?: Record<string, string | number>) => string;
  setLanguage: (lang: string) => void;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: 'en',
  t: (key: string) => key,
  setLanguage: () => {},
});

interface LanguageProviderProps {
  children: React.ReactNode;
}

const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>(localStorage.getItem('language') || 'en');

  React.useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const translations = {
    en: {
      // General
      search: 'Search',
      booking: 'Booking',
      tracking: 'Tracking',
      services: 'Services',
      contact: 'Contact',
      login: 'Login',
      logout: 'Logout',
      dashboard: 'Dashboard',
      profile: 'Profile',
      settings: 'Settings',
      notifications: 'Notifications',
      shipment: 'Shipment',
      id: 'ID',
      status: 'Status',
      date: 'Date',
      location: 'Location',
      details: 'Details',
      viewAll: 'View All',
      allRightsReserved: 'All Rights Reserved',
      back: 'Back',
      next: 'Next',
      submit: 'Submit',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      origin: 'Origin',
      destination: 'Destination',
      description: 'Description',
      containerCount: 'Container Count',
      weight: 'Weight',
      estimatedDelivery: 'Estimated Delivery',
      units: 'Units',
      costBreakdown: 'Cost Breakdown',
      freightCost: 'Freight Cost',
      handlingFees: 'Handling Fees',
      documentation: 'Documentation',
      insurance: 'Insurance',
      totalAmount: 'Total Amount',
      securePayment: 'Secure Payment',
      paymentDesc: 'Please review your shipment details and complete the payment to proceed.',
      loadingPayment: 'Loading payment information...',
      paymentSuccessful: 'Payment Successful!',
      paymentFailed: 'Payment Failed!',
      shipmentId: 'Shipment ID',
      enterBookingReference: 'Enter Booking Reference',
      verifyBookingDesc: 'Please enter your booking reference to verify your shipment details.',
      bookingReference: 'Booking Reference',
      enterReferenceNumber: 'Enter your reference number',
      verify: 'Verify',
      verifying: 'Verifying...',
      verified: 'Verified',
      paymentDetails: 'Payment Details',
      cardDetails: 'Card Details',
      enterBookingReferenceAndCardDetails: "Enter your booking reference and card details below to complete your secure payment.",
      completePaymentDetails: "Complete your payment details to finalize your shipping transaction",
      selectPaymentMethod: "Select Payment Method",
      creditDebitCard: 'Credit / Debit Card',
      mobileMoney: 'Mobile Money',
      phoneNumber: 'Phone Number',
      enterPhoneNumber: 'Enter your phone number',
      paypalEmail: 'PayPal Email',
      enterPaypalEmail: 'Enter your PayPal email',
      pay: 'Pay',
      processing: 'Processing...',
      choosePaymentMethod: 'Choose your payment method',
      // Index page translations
      heroTitle: 'Your reliable partner for global logistics',
      heroSubtitle: 'We offer comprehensive solutions for all your shipping needs, worldwide.',
      getStarted: 'Get Started',
      trackYourShipment: 'Track Your Shipment',
      enterTrackingNumber: 'Enter your tracking number',
      track: 'Track',
      whyChooseUs: 'Why Choose Us?',
      globalNetwork: 'Global Network',
      globalNetworkDescription: 'Extensive network of partners worldwide for seamless shipping.',
      fastDelivery: 'Fast Delivery',
      fastDeliveryDescription: 'Reliable and efficient delivery services to meet your deadlines.',
      secureHandling: 'Secure Handling',
      secureHandlingDescription: 'Safe and secure handling of your goods from start to finish.',
      customerSupport: '24/7 Customer Support',
      customerSupportDescription: 'Dedicated support team available around the clock to assist you.',
      // Booking page translations
      bookAShipment: 'Book a Shipment',
      senderInformation: 'Sender Information',
      recipientInformation: 'Recipient Information',
      shipmentDetailsInformation: 'Shipment Details',
      firstName: 'First Name',
      lastName: 'Last Name',
      companyName: 'Company Name',
      emailAddress: 'Email Address',
      phoneNumberOptional: 'Phone Number (Optional)',
      addressLine1: 'Address Line 1',
      addressLine2Optional: 'Address Line 2 (Optional)',
      city: 'City',
      stateProvinceRegion: 'State / Province / Region',
      zipPostalCode: 'Zip / Postal Code',
      country: 'Country',
      packageType: 'Package Type',
      selectPackageType: 'Select Package Type',
      numberOfPackages: 'Number of Packages',
      totalWeight: 'Total Weight',
      dimensionsPerPackage: 'Dimensions per Package (cm)',
      length: 'Length',
      width: 'Width',
      height: 'Height',
      descriptionOfContents: 'Description of Contents',
      termsAndConditions: 'I agree to the terms and conditions',
      // Tracking page translations
      trackShipmentStatus: 'Track Shipment Status',
      enterTrackingNumberGetUpdates: 'Enter your tracking number to get the latest updates on your shipment.',
      // Services page translations
      ourServices: 'Our Services',
      comprehensiveSolutions: 'Comprehensive Solutions',
      comprehensiveSolutionsDescription: 'We provide end-to-end logistics solutions tailored to your needs.',
      warehousing: 'Warehousing',
      warehousingDescription: 'Secure and efficient warehousing services for your inventory management.',
      customsClearance: 'Customs Clearance',
      customsClearanceDescription: 'Expert customs clearance services to ensure smooth border crossing.',
      supplyChainManagement: 'Supply Chain Management',
      supplyChainManagementDescription: 'Optimize your supply chain with our integrated management solutions.',
      // Contact page translations
      contactUs: 'Contact Us',
      getInTouch: 'Get in touch with us for any inquiries or support.',
      fullName: 'Full Name',
      yourEmail: 'Your Email',
      message: 'Message',
      sendMessage: 'Send Message',
      // Passengers page translations
      managePassengers: 'Manage Passengers',
      addPassengerDetails: 'Add passenger details for your booking.',
      passengerInformation: 'Passenger Information',
      dateOfBirth: 'Date of Birth',
      passportNumber: 'Passport Number',
      expiryDate: 'Expiry Date',
      addPassenger: 'Add Passenger',
      // Not Found page translations
      pageNotFound: 'Page Not Found',
      oops: 'Oops! The page you are looking for could not be found.',
      goHome: 'Go Home',
      // Supplier Payment page translations
      supplierPaymentPortal: 'Supplier Payment Portal',
      enterInvoiceDetails: 'Enter invoice details to process payment.',
      invoiceNumber: 'Invoice Number',
      amountDue: 'Amount Due',
      payNow: 'Pay Now',
    },
    fr: {
      // General
      search: 'Rechercher',
      booking: 'Réservation',
      tracking: 'Suivi',
      services: 'Services',
      contact: 'Contact',
      login: 'Se connecter',
      logout: 'Se déconnecter',
      dashboard: 'Tableau de bord',
      profile: 'Profil',
      settings: 'Paramètres',
      notifications: 'Notifications',
      shipment: 'Expédition',
      id: 'ID',
      status: 'Statut',
      date: 'Date',
      location: 'Emplacement',
      details: 'Détails',
      viewAll: 'Voir tout',
      allRightsReserved: 'Tous droits réservés',
      back: 'Retour',
      next: 'Suivant',
      submit: 'Soumettre',
      loading: 'Chargement...',
      error: 'Erreur',
      success: 'Succès',
      origin: 'Origine',
      destination: 'Destination',
      description: 'Description',
      containerCount: 'Nombre de conteneurs',
      weight: 'Poids',
      estimatedDelivery: 'Livraison estimée',
      units: 'Unités',
      costBreakdown: 'Répartition des coûts',
      freightCost: 'Frais de transport',
      handlingFees: 'Frais de manutention',
      documentation: 'Documentation',
      insurance: 'Assurance',
      totalAmount: 'Montant total',
      securePayment: 'Paiement sécurisé',
      paymentDesc: 'Veuillez vérifier les détails de votre envoi et effectuer le paiement pour continuer.',
      loadingPayment: 'Chargement des informations de paiement...',
      paymentSuccessful: 'Paiement réussi!',
      paymentFailed: 'Paiement échoué!',
      shipmentId: 'ID de l\'expédition',
      enterBookingReference: 'Entrez la référence de réservation',
      verifyBookingDesc: 'Veuillez entrer votre référence de réservation pour vérifier les détails de votre envoi.',
      bookingReference: 'Référence de réservation',
      enterReferenceNumber: 'Entrez votre numéro de référence',
      verify: 'Vérifier',
      verifying: 'Vérification...',
      verified: 'Vérifié',
      paymentDetails: 'Détails de paiement',
      cardDetails: 'Détails de la carte',
      enterBookingReferenceAndCardDetails: "Entrez votre référence de réservation et les détails de votre carte ci-dessous pour finaliser votre paiement sécurisé.",
      completePaymentDetails: "Complétez vos informations de paiement pour finaliser votre transaction d'expédition",
      selectPaymentMethod: "Sélectionnez le mode de paiement",
      creditDebitCard: 'Carte de crédit / débit',
      mobileMoney: 'Argent mobile',
      phoneNumber: 'Numéro de téléphone',
      enterPhoneNumber: 'Entrez votre numéro de téléphone',
      paypalEmail: 'Email PayPal',
      enterPaypalEmail: 'Entrez votre email PayPal',
      pay: 'Payer',
      processing: 'Traitement...',
      choosePaymentMethod: 'Choisissez votre méthode de paiement',
      // Index page translations
      heroTitle: 'Votre partenaire fiable pour la logistique mondiale',
      heroSubtitle: 'Nous offrons des solutions complètes pour tous vos besoins d\'expédition, dans le monde entier.',
      getStarted: 'Commencer',
      trackYourShipment: 'Suivre votre envoi',
      enterTrackingNumber: 'Entrez votre numéro de suivi',
      track: 'Suivre',
      whyChooseUs: 'Pourquoi nous choisir?',
      globalNetwork: 'Réseau mondial',
      globalNetworkDescription: 'Vaste réseau de partenaires dans le monde entier pour une expédition sans faille.',
      fastDelivery: 'Livraison rapide',
      fastDeliveryDescription: 'Services de livraison fiables et efficaces pour respecter vos délais.',
      secureHandling: 'Manutention sécurisée',
      secureHandlingDescription: 'Manutention sûre et sécurisée de vos marchandises du début à la fin.',
      customerSupport: 'Support client 24/7',
      customerSupportDescription: 'Équipe de support dédiée disponible 24 heures sur 24 pour vous aider.',
      // Booking page translations
      bookAShipment: 'Réserver un envoi',
      senderInformation: 'Informations sur l\'expéditeur',
      recipientInformation: 'Informations sur le destinataire',
      shipmentDetailsInformation: 'Détails de l\'envoi',
      firstName: 'Prénom',
      lastName: 'Nom de famille',
      companyName: 'Nom de l\'entreprise',
      emailAddress: 'Adresse e-mail',
      phoneNumberOptional: 'Numéro de téléphone (facultatif)',
      addressLine1: 'Adresse ligne 1',
      addressLine2Optional: 'Adresse ligne 2 (facultatif)',
      city: 'Ville',
      stateProvinceRegion: 'État / Province / Région',
      zipPostalCode: 'Code postal',
      country: 'Pays',
      packageType: 'Type de colis',
      selectPackageType: 'Sélectionner le type de colis',
      numberOfPackages: 'Nombre de colis',
      totalWeight: 'Poids total',
      dimensionsPerPackage: 'Dimensions par colis (cm)',
      length: 'Longueur',
      width: 'Largeur',
      height: 'Hauteur',
      descriptionOfContents: 'Description du contenu',
      termsAndConditions: 'J\'accepte les termes et conditions',
      // Tracking page translations
      trackShipmentStatus: 'Suivre l\'état de l\'envoi',
      enterTrackingNumberGetUpdates: 'Entrez votre numéro de suivi pour obtenir les dernières mises à jour sur votre envoi.',
      // Services page translations
      ourServices: 'Nos services',
      comprehensiveSolutions: 'Solutions complètes',
      comprehensiveSolutionsDescription: 'Nous fournissons des solutions logistiques de bout en bout adaptées à vos besoins.',
      warehousing: 'Entreposage',
      warehousingDescription: 'Services d\'entreposage sécurisés et efficaces pour la gestion de votre inventaire.',
      customsClearance: 'Dédouanement',
      customsClearanceDescription: 'Services de dédouanement experts pour assurer un passage frontalier en douceur.',
      supplyChainManagement: 'Gestion de la chaîne d\'approvisionnement',
      supplyChainManagementDescription: 'Optimisez votre chaîne d\'approvisionnement grâce à nos solutions de gestion intégrées.',
      // Contact page translations
      contactUs: 'Contactez-nous',
      getInTouch: 'Contactez-nous pour toute question ou assistance.',
      fullName: 'Nom complet',
      yourEmail: 'Votre e-mail',
      message: 'Message',
      sendMessage: 'Envoyer le message',
      // Passengers page translations
      managePassengers: 'Gérer les passagers',
      addPassengerDetails: 'Ajouter les détails des passagers pour votre réservation.',
      passengerInformation: 'Informations sur le passager',
      dateOfBirth: 'Date de naissance',
      passportNumber: 'Numéro de passeport',
      expiryDate: 'Date d\'expiration',
      addPassenger: 'Ajouter un passager',
      // Not Found page translations
      pageNotFound: 'Page non trouvée',
      oops: 'Oops! La page que vous recherchez n\'a pas pu être trouvée.',
      goHome: 'Retour à l\'accueil',
      // Supplier Payment page translations
      supplierPaymentPortal: 'Portail de paiement des fournisseurs',
      enterInvoiceDetails: 'Entrez les détails de la facture pour traiter le paiement.',
      invoiceNumber: 'Numéro de facture',
      amountDue: 'Montant dû',
      payNow: 'Payer maintenant',
    },
    es: {
      // General
      search: 'Buscar',
      booking: 'Reserva',
      tracking: 'Seguimiento',
      services: 'Servicios',
      contact: 'Contacto',
      login: 'Iniciar sesión',
      logout: 'Cerrar sesión',
      dashboard: 'Panel de control',
      profile: 'Perfil',
      settings: 'Configuración',
      notifications: 'Notificaciones',
      shipment: 'Envío',
      id: 'ID',
      status: 'Estado',
      date: 'Fecha',
      location: 'Ubicación',
      details: 'Detalles',
      viewAll: 'Ver todo',
      allRightsReserved: 'Todos los derechos reservados',
      back: 'Atrás',
      next: 'Siguiente',
      submit: 'Enviar',
      loading: 'Cargando...',
      error: 'Error',
      success: 'Éxito',
      origin: 'Origen',
      destination: 'Destino',
      description: 'Descripción',
      containerCount: 'Cantidad de contenedores',
      weight: 'Peso',
      estimatedDelivery: 'Entrega estimada',
      units: 'Unidades',
      costBreakdown: 'Desglose de costos',
      freightCost: 'Costo de flete',
      handlingFees: 'Gastos de manipulación',
      documentation: 'Documentación',
      insurance: 'Seguro',
      totalAmount: 'Monto total',
      securePayment: 'Pago seguro',
      paymentDesc: 'Por favor, revise los detalles de su envío y complete el pago para continuar.',
      loadingPayment: 'Cargando información de pago...',
      paymentSuccessful: '¡Pago exitoso!',
      paymentFailed: '¡Pago fallido!',
      shipmentId: 'ID del envío',
      enterBookingReference: 'Ingrese la referencia de la reserva',
      verifyBookingDesc: 'Por favor, ingrese su referencia de reserva para verificar los detalles de su envío.',
      bookingReference: 'Referencia de la reserva',
      enterReferenceNumber: 'Ingrese su número de referencia',
      verify: 'Verificar',
      verifying: 'Verificando...',
      verified: 'Verificado',
      paymentDetails: 'Detalles de pago',
      cardDetails: 'Detalles de la tarjeta',
      enterBookingReferenceAndCardDetails: "Ingrese su referencia de reserva y los detalles de su tarjeta a continuación para completar su pago seguro.",
      completePaymentDetails: "Complete sus datos de pago para finalizar su transacción de envío",
      selectPaymentMethod: "Seleccione el método de pago",
      creditDebitCard: 'Tarjeta de crédito / débito',
      mobileMoney: 'Dinero móvil',
      phoneNumber: 'Número de teléfono',
      enterPhoneNumber: 'Ingrese su número de teléfono',
      paypalEmail: 'Correo electrónico de PayPal',
      enterPaypalEmail: 'Ingrese su correo electrónico de PayPal',
      pay: 'Pagar',
      processing: 'Procesando...',
      choosePaymentMethod: 'Elija su método de pago',
      // Index page translations
      heroTitle: 'Su socio confiable para la logística global',
      heroSubtitle: 'Ofrecemos soluciones integrales para todas sus necesidades de envío, en todo el mundo.',
      getStarted: 'Comenzar',
      trackYourShipment: 'Rastree su envío',
      enterTrackingNumber: 'Ingrese su número de seguimiento',
      track: 'Rastrear',
      whyChooseUs: '¿Por qué elegirnos?',
      globalNetwork: 'Red global',
      globalNetworkDescription: 'Amplia red de socios en todo el mundo para un envío sin problemas.',
      fastDelivery: 'Entrega rápida',
      fastDeliveryDescription: 'Servicios de entrega confiables y eficientes para cumplir con sus plazos.',
      secureHandling: 'Manejo seguro',
      secureHandlingDescription: 'Manejo seguro y protegido de sus productos de principio a fin.',
      customerSupport: 'Atención al cliente 24/7',
      customerSupportDescription: 'Equipo de soporte dedicado disponible las 24 horas para ayudarlo.',
      // Booking page translations
      bookAShipment: 'Reservar un envío',
      senderInformation: 'Información del remitente',
      recipientInformation: 'Información del destinatario',
      shipmentDetailsInformation: 'Detalles del envío',
      firstName: 'Nombre',
      lastName: 'Apellido',
      companyName: 'Nombre de la empresa',
      emailAddress: 'Dirección de correo electrónico',
      phoneNumberOptional: 'Número de teléfono (opcional)',
      addressLine1: 'Dirección línea 1',
      addressLine2Optional: 'Dirección línea 2 (opcional)',
      city: 'Ciudad',
      stateProvinceRegion: 'Estado / Provincia / Región',
      zipPostalCode: 'Código postal',
      country: 'País',
      packageType: 'Tipo de paquete',
      selectPackageType: 'Seleccionar tipo de paquete',
      numberOfPackages: 'Número de paquetes',
      totalWeight: 'Peso total',
      dimensionsPerPackage: 'Dimensiones por paquete (cm)',
      length: 'Longitud',
      width: 'Ancho',
      height: 'Altura',
      descriptionOfContents: 'Descripción del contenido',
      termsAndConditions: 'Acepto los términos y condiciones',
      // Tracking page translations
      trackShipmentStatus: 'Rastrear el estado del envío',
      enterTrackingNumberGetUpdates: 'Ingrese su número de seguimiento para obtener las últimas actualizaciones sobre su envío.',
      // Services page translations
      ourServices: 'Nuestros servicios',
      comprehensiveSolutions: 'Soluciones integrales',
      comprehensiveSolutionsDescription: 'Proporcionamos soluciones logísticas integrales adaptadas a sus necesidades.',
      warehousing: 'Almacenamiento',
      warehousingDescription: 'Servicios de almacenamiento seguros y eficientes para la gestión de su inventario.',
      customsClearance: 'Despacho de aduanas',
      customsClearanceDescription: 'Servicios expertos de despacho de aduanas para garantizar un cruce fronterizo sin problemas.',
      supplyChainManagement: 'Gestión de la cadena de suministro',
      supplyChainManagementDescription: 'Optimice su cadena de suministro con nuestras soluciones de gestión integradas.',
      // Contact page translations
      contactUs: 'Contáctenos',
      getInTouch: 'Póngase en contacto con nosotros para cualquier consulta o soporte.',
      fullName: 'Nombre completo',
      yourEmail: 'Su correo electrónico',
      message: 'Mensaje',
      sendMessage: 'Enviar mensaje',
      // Passengers page translations
      managePassengers: 'Gestionar pasajeros',
      addPassengerDetails: 'Agregar detalles de los pasajeros para su reserva.',
      passengerInformation: 'Información del pasajero',
      dateOfBirth: 'Fecha de nacimiento',
      passportNumber: 'Número de pasaporte',
      expiryDate: 'Fecha de caducidad',
      addPassenger: 'Agregar pasajero',
      // Not Found page translations
      pageNotFound: 'Página no encontrada',
      oops: '¡Oops! No se pudo encontrar la página que está buscando.',
      goHome: 'Ir a la página de inicio',
      // Supplier Payment page translations
      supplierPaymentPortal: 'Portal de pago para proveedores',
      enterInvoiceDetails: 'Ingrese los detalles de la factura para procesar el pago.',
      invoiceNumber: 'Número de factura',
      amountDue: 'Monto adeudado',
      payNow: 'Pagar ahora',
    },
  };

  const t = useCallback(
    (key: string, params: Record<string, string | number> = {}) => {
      let translation = translations[language as keyof typeof translations][key] || key;
      
      Object.keys(params).forEach(paramKey => {
        translation = translation.replace(`{{${paramKey}}}`, String(params[paramKey]));
      });

      return translation;
    },
    [language]
  );

  const value = {
    language,
    t,
    setLanguage,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export { LanguageProvider, useLanguage };
